create table public.my_new_table (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);
alter table public.my_new_table enable row level security;
