create table public.my_new_table_4 (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create index my_new_table_user_id_idx on public.my_new_table_4 (user_id);

alter table public.my_new_table_4 enable row level security;